"""add patronymic to player and player_league_status table

Revision ID: 0f927c645981
Revises: 2cda1119b3c9
Create Date: 2025-05-17 22:43:54.396232

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0f927c645981'
down_revision = '2cda1119b3c9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('player_league_statuses',
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('league_id', sa.Integer(), nullable=False),
    sa.Column('is_foreign', sa.Boolean(), nullable=False),
    sa.Column('is_self', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['league_id'], ['leagues.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('player_id', 'league_id', name='_player_league_uc')
    )
    op.create_index(op.f('ix_player_league_statuses_id'), 'player_league_statuses', ['id'], unique=False)
    op.add_column('players', sa.Column('patronymic', sa.String(), nullable=True))
    op.alter_column('teams', 'country',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('teams', 'country',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('players', 'patronymic')
    op.drop_index(op.f('ix_player_league_statuses_id'), table_name='player_league_statuses')
    op.drop_table('player_league_statuses')
    # ### end Alembic commands ### 