"""add fields to tournament_team_players: number, is_foreign, is_self, registered, unregistered

Revision ID: 4301cbc4543a
Revises: e903d2fa5955
Create Date: 2025-05-17 23:23:04.335694

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4301cbc4543a'
down_revision = 'e903d2fa5955'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tournament_team_players', sa.Column('number', sa.Integer(), nullable=True))
    op.add_column('tournament_team_players', sa.Column('is_foreign', sa.Boolean(), nullable=False))
    op.add_column('tournament_team_players', sa.Column('is_self', sa.Boolean(), nullable=False))
    op.add_column('tournament_team_players', sa.Column('registered', sa.String(), nullable=True))
    op.add_column('tournament_team_players', sa.Column('unregistered', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tournament_team_players', 'unregistered')
    op.drop_column('tournament_team_players', 'registered')
    op.drop_column('tournament_team_players', 'is_self')
    op.drop_column('tournament_team_players', 'is_foreign')
    op.drop_column('tournament_team_players', 'number')
    # ### end Alembic commands ### 