"""add rounds_count to tournaments

Revision ID: 464332b3a380
Revises: 7fe47f99c070
Create Date: 2025-05-17 20:21:13.120649

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '464332b3a380'
down_revision = '7fe47f99c070'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tournaments', sa.Column('rounds_count', sa.Integer(), nullable=False, server_default='1'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tournaments', 'rounds_count')
    # ### end Alembic commands ### 