"""add_tour_dates_to_tournaments

Revision ID: 5a6724c9eea8
Revises: a2aac3d40681
Create Date: 2025-05-21 08:47:47.543171

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a6724c9eea8'
down_revision = 'a2aac3d40681'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ### 