"""add_format_field_to_tournaments

Revision ID: 72ed939f66e9
Revises: b69f84642959
Create Date: 2025-05-19 10:41:19.244790

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '72ed939f66e9'
down_revision = 'b69f84642959'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tournaments', sa.Column('format', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tournaments', 'format')
    # ### end Alembic commands ### 