"""remove nationality and add phone to player

Revision ID: 836cfca266c8
Revises: 4301cbc4543a
Create Date: 2025-05-17 23:49:44.192483

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '836cfca266c8'
down_revision = '4301cbc4543a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('players', sa.Column('phone', sa.String(), nullable=True))
    op.drop_column('players', 'nationality')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('players', sa.Column('nationality', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('players', 'phone')
    # ### end Alembic commands ### 