"""add_matches_table

Revision ID: 968bd82527dd
Revises: 4eee6e7244dd
Create Date: 2025-05-16 00:00:39.579467

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '968bd82527dd'
down_revision = '4eee6e7244dd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('matches',
    sa.Column('tournament_id', sa.Integer(), nullable=True),
    sa.Column('home_team_id', sa.Integer(), nullable=False),
    sa.Column('away_team_id', sa.Integer(), nullable=False),
    sa.Column('stadium_id', sa.Integer(), nullable=True),
    sa.Column('match_date', sa.Date(), nullable=False),
    sa.Column('match_time', sa.DateTime(), nullable=True),
    sa.Column('home_score', sa.Integer(), nullable=True),
    sa.Column('away_score', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('SCHEDULED', 'LIVE', 'FINISHED', 'POSTPONED', 'CANCELED', name='matchstatus'), nullable=False),
    sa.Column('round', sa.String(), nullable=True),
    sa.Column('attendance', sa.Integer(), nullable=True),
    sa.Column('referee', sa.String(), nullable=True),
    sa.Column('is_extra_time', sa.Boolean(), nullable=True),
    sa.Column('is_penalty', sa.Boolean(), nullable=True),
    sa.Column('home_penalty_score', sa.Integer(), nullable=True),
    sa.Column('away_penalty_score', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['away_team_id'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['home_team_id'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['stadium_id'], ['stadiums.id'], ),
    sa.ForeignKeyConstraint(['tournament_id'], ['tournaments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_matches_id'), 'matches', ['id'], unique=False)
    op.create_index(op.f('ix_matches_match_date'), 'matches', ['match_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_matches_match_date'), table_name='matches')
    op.drop_index(op.f('ix_matches_id'), table_name='matches')
    op.drop_table('matches')
    # ### end Alembic commands ### 