"""add_tour_dates_to_tournaments

Revision ID: a2aac3d40681
Revises: 72ed939f66e9
Create Date: 2025-05-21 08:21:45.659715

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a2aac3d40681'
down_revision = '72ed939f66e9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tournaments', sa.Column('tour_dates', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tournaments', 'tour_dates')
    # ### end Alembic commands ### 