"""update_teams_table

Revision ID: b1630ab52c06
Revises: e98f2cf96b3d
Create Date: 2025-05-15 23:41:26.756740

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b1630ab52c06'
down_revision = 'e98f2cf96b3d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teams', sa.Column('city_id', sa.Integer(), nullable=True))
    op.add_column('teams', sa.Column('stadium_id', sa.Integer(), nullable=True))
    op.add_column('teams', sa.Column('league_id', sa.Integer(), nullable=True))
    op.add_column('teams', sa.Column('founded_year', sa.Integer(), nullable=True))
    op.add_column('teams', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('teams', sa.Column('website', sa.String(), nullable=True))
    op.create_foreign_key(None, 'teams', 'cities', ['city_id'], ['id'])
    op.create_foreign_key(None, 'teams', 'leagues', ['league_id'], ['id'])
    op.create_foreign_key(None, 'teams', 'stadiums', ['stadium_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'teams', type_='foreignkey')
    op.drop_constraint(None, 'teams', type_='foreignkey')
    op.drop_constraint(None, 'teams', type_='foreignkey')
    op.drop_column('teams', 'website')
    op.drop_column('teams', 'description')
    op.drop_column('teams', 'founded_year')
    op.drop_column('teams', 'league_id')
    op.drop_column('teams', 'stadium_id')
    op.drop_column('teams', 'city_id')
    # ### end Alembic commands ### 