"""add referee model and relation to match

Revision ID: b69f84642959
Revises: 836cfca266c8
Create Date: 2025-05-18 08:40:49.626573

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b69f84642959'
down_revision = '836cfca266c8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('referees',
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('patronymic', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_referees_id'), 'referees', ['id'], unique=False)
    op.create_index(op.f('ix_referees_last_name'), 'referees', ['last_name'], unique=False)
    op.add_column('matches', sa.Column('referee_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'matches', 'referees', ['referee_id'], ['id'])
    op.drop_column('matches', 'referee')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('matches', sa.Column('referee', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'matches', type_='foreignkey')
    op.drop_column('matches', 'referee_id')
    op.drop_index(op.f('ix_referees_last_name'), table_name='referees')
    op.drop_index(op.f('ix_referees_id'), table_name='referees')
    op.drop_table('referees')
    # ### end Alembic commands ### 