"""add_stadiums_table

Revision ID: e98f2cf96b3d
Revises: 5de60c0b0033
Create Date: 2025-05-15 23:37:39.518894

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e98f2cf96b3d'
down_revision = '5de60c0b0033'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stadiums',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('city_id', sa.Integer(), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('photo_url', sa.String(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['city_id'], ['cities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stadiums_id'), 'stadiums', ['id'], unique=False)
    op.create_index(op.f('ix_stadiums_name'), 'stadiums', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_stadiums_name'), table_name='stadiums')
    op.drop_index(op.f('ix_stadiums_id'), table_name='stadiums')
    op.drop_table('stadiums')
    # ### end Alembic commands ### 