"""add coach to teams

Revision ID: f51d668d8a5f
Revises: 968bd82527dd
Create Date: 2025-05-17 19:32:48.294194

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f51d668d8a5f'
down_revision = '968bd82527dd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('match_stats',
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('minutes_played', sa.Integer(), nullable=True),
    sa.Column('goals', sa.Integer(), nullable=True),
    sa.Column('assists', sa.Integer(), nullable=True),
    sa.Column('yellow_cards', sa.Integer(), nullable=True),
    sa.Column('red_card', sa.Boolean(), nullable=True),
    sa.Column('goal_minutes', sa.String(), nullable=True),
    sa.Column('goal_types', sa.String(), nullable=True),
    sa.Column('card_minutes', sa.String(), nullable=True),
    sa.Column('card_types', sa.String(), nullable=True),
    sa.Column('shots', sa.Integer(), nullable=True),
    sa.Column('shots_on_target', sa.Integer(), nullable=True),
    sa.Column('fouls_committed', sa.Integer(), nullable=True),
    sa.Column('fouls_suffered', sa.Integer(), nullable=True),
    sa.Column('saves', sa.Integer(), nullable=True),
    sa.Column('offsides', sa.Integer(), nullable=True),
    sa.Column('corners_won', sa.Integer(), nullable=True),
    sa.Column('is_started', sa.Boolean(), nullable=True),
    sa.Column('is_substitute', sa.Boolean(), nullable=True),
    sa.Column('substitute_in_minute', sa.Integer(), nullable=True),
    sa.Column('substitute_out_minute', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_match_stats_id'), 'match_stats', ['id'], unique=False)
    op.add_column('teams', sa.Column('coach', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('teams', 'coach')
    op.drop_index(op.f('ix_match_stats_id'), table_name='match_stats')
    op.drop_table('match_stats')
    # ### end Alembic commands ### 