name: CI

on:
  push:
    branches: [ main, master, develop ]
  pull_request:
    branches: [ main, master, develop ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install black flake8 isort
          if [ -f backend/requirements-dev.txt ]; then pip install -r backend/requirements-dev.txt; fi
      - name: Lint with flake8
        run: flake8 backend/app
      - name: Check formatting with black
        run: black --check backend/app
      - name: Check imports with isort
        run: isort --check-only --profile black backend/app

  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:17
        env:
          POSTGRES_PASSWORD: pam
          POSTGRES_USER: admin
          POSTGRES_DB: football_test
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          cd backend
          pip install -r requirements.txt
          pip install -r requirements-dev.txt
      - name: Test with pytest
        run: |
          cd backend
          pytest --cov=app tests/
        env:
          DATABASE_URL: postgresql://admin:pam@192.168.1.124:5432/football_test 